### ISSUE TITLE
install.sh报错

### ISSUE THREAD

**Issue by SlippyJimmy** [glepnir/nvim#10]
![image](https://user-images.githubusercontent.com/45062658/107513216-d8dbda80-6be2-11eb-945d-86c02fc3ce01.png)
lenguages.toml中多了一行```,
![image](https://user-images.githubusercontent.com/45062658/107513308-0163d480-6be3-11eb-838c-69668926a9f8.png)
go-nvim的reps没了，请问我该换成什么

**Comment by glepnir** [comment]
vim-go
