### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by SlippyJimmy** [glepnir/nvim#13]
![image](https://user-images.githubusercontent.com/45062658/109304607-77b93580-7877-11eb-9040-88a14f8a33f6.png)
![image](https://user-images.githubusercontent.com/45062658/109304616-7b4cbc80-7877-11eb-9d28-2423faf8e105.png)

**Comment by glepnir** [comment]
hmmm open nvim it will auto install. not use makefile.

**Comment by SlippyJimmy** [comment]
thanks,I have got sloved it. But there are another bug when i use it.
![image](https://user-images.githubusercontent.com/45062658/109389912-896b0d80-7949-11eb-9ded-cc0edc49e38a.png)
when I save '.go' file，will
![image](https://user-images.githubusercontent.com/45062658/109389958-cc2ce580-7949-11eb-9270-1ecdfb71fb86.png)

>

**Comment by SlippyJimmy** [comment]
I am using your dotfiles and nvim config，but Lsp not work..
![image](https://user-images.githubusercontent.com/45062658/109390063-62f9a200-794a-11eb-8848-5bc95bcad307.png)
![image](https://user-images.githubusercontent.com/45062658/109390081-7a388f80-794a-11eb-896d-415db67161ff.png)There are Lspinfo and Lsplog.
