### ISSUE TITLE
An error when press tab.

### ISSUE THREAD

**Issue by Adnios** [glepnir/nvim#14]
# Reproduce
`nvim test.lua`
Enter the Insert mode. Type '1' and press tab
![image](https://user-images.githubusercontent.com/41060790/110201385-bcf3ed80-7e9d-11eb-9cb2-db2db9259a33.png)
![image](https://user-images.githubusercontent.com/41060790/110201413-e44aba80-7e9d-11eb-9b6c-d8f4c4255655.png)
I think that this error can be solve by install snippets.nvim plug. Not sure.
```
completion['norcalli/snippets.nvim'] = {
  event = 'InsertEnter',
}
```

**Comment by glepnir** [comment]
this is my person config. maybe not work for other people and I don't work with this repo issue. close.
