### ISSUE TITLE
Startuptime not as fast as described

### ISSUE THREAD

**Issue by shaunsingh** [glepnir/nvim#22]
When running `time neovim +q`, the fastest result I get is 

```
real    0m0,160s
user    0m0,123s
sys    0m0,037s
```

Only reason I was wondering is because I was looking to speed up my own config as well, but even without any lazy loading and a decently long plugin list, its still a tad bit faster than yours

**Comment by rebuilt** [comment]
I'm also curious about this. I assumed it was measured on a faster machine than mine.  Did you measure with nvim --startuptime as well?

**Comment by shaunsingh** [comment]
with `nvim --startuptime` it shows 158ms total, which is about the same. 

My machine is an m1 MacBook Pro, the ssd reads at about 2.6gb/s, so I don't think that should be the issue either.

**Comment by rebuilt** [comment]
Is your drive encrypted?   

I get about 55ms for the default config.  But I'm on a 1920x threadripper and an nvme drive

**Comment by shaunsingh** [comment]
My drive is unencrypted, but it might be because of macOS.

**Comment by rebuilt** [comment]
Are you on 0.5 or 0.4 of neovim?

**Comment by rebuilt** [comment]
If you pull up the activity monitor, does the architecture for neovim say apple?   If so, it's running natively.  If not, it's running under rosetta.

**Comment by shaunsingh** [comment]
I was using 0.5 and neovim/alacritty/fish were all installed natively

I'm not sure what happened but recently it became much faster. It might've been a bug upstream with neovim. Thanks for all the help!
