### ISSUE TITLE
启动 错误

### ISSUE THREAD

**Issue by terryzhouke** [glepnir/nvim#26]
windows 环境下 neovim 0.5.1 
![Snipaste_2021-10-16_10-57-30](https://user-images.githubusercontent.com/6236896/137571361-07218e1f-04c4-4554-a16b-b1c0ef8dbab8.jpg)

使用配置出现上述错误，查了网上信息。有类似问题的反馈原因是 
vim.g.dashboard_custom_section 的配置不规范导致[https://github.com/glepnir/dashboard-nvim/issues/106](url)
两个问题：
1、是否跟上面的链接问题是一样的‘？
2、没有在nvim配置里面找到在哪里修改

**Comment by glepnir** [comment]
install lolcat
