### ISSUE TITLE
arithmetic on a nil value

### ISSUE THREAD

**Issue by Astrantia** [glepnir/nvim#39]
Hi. I'm using dashboard only for the header, without any navigation. This is my config:

```lua
dashboard.custom_footer = { [[]] }
dashboard.custom_center = { {} }
```

The first time dashboard opens without an error, but after switching a buffer and running `:Dashboard` i get the following error:

```
Error executing Lua callback: ...share/nvim/plugged/dashboard-nvim/lua/dashboard/init.lua:342: attempt to perform arithmetic on a nil value
stack traceback:
        ...share/nvim/plugged/dashboard-nvim/lua/dashboard/init.lua:342: in function 'load_from_cache'
        ...share/nvim/plugged/dashboard-nvim/lua/dashboard/init.lua:390: in function 'instance'
        ...l/share/nvim/plugged/dashboard-nvim/plugin/dashboard.lua:63: in function <...l/share/nvim/plugged/dashboard-nvim/plugin/dashboard.lua:62>
```

Separate issue, but related to this: since I don't have any need for navigation with `hjkl` I want to map `l` to edit my lua init file, but it doesn't look possible:

`au FileType dashboard nnoremap <buffer> <silent>l :e ~/.config/nvim/lua/init.lua<CR>` <-- this doesn't work in the new version, but it used to work fine in the past.

**Comment by glepnir** [comment]
use 
```
db.custom_center = { {desc = ' ' }}
db.custom_footer = { ' '}
```
