### ISSUE TITLE
之前是可以用的 ,clone了最新版启动有问题...

### ISSUE THREAD

**Issue by LiamBao** [glepnir/nvim#40]
Run PackerInstall
Error detected while processing function <SNR>24_loaded_dashboard[3]..dashboard#instance[73]..<SNR>28_print_plugins_message:
line   18:
E5108: Error executing lua vim/shared.lua:0: Expected table, got nil
stack traceback:
        [C]: in function 'assert'
        vim/shared.lua: in function 'tbl_keys'
        [string "luaeval()"]:1: in main chunk
Press ENTER or type command to continue
Error detected while processing function <SNR>24_loaded_dashboard[3]..dashboard#instance[73]..dashboard#utils#draw_center:
line    1:
E896: Argument of map() must be a List, Dictionary or Blob
Press ENTER or type command to continue
Error detected while processing function <SNR>24_loaded_dashboard[3]..dashboard#instance[73]..dashboard#utils#draw_center:
line    1:
E712: Argument of max() must be a List or Dictionary
Press ENTER or type command to continue

**Comment by glepnir** [comment]
你这个好老了吧。。我dashbaord都重写了。 neovim 用nightly
