### ISSUE TITLE
Windows 下的几个问题

### ISSUE THREAD

**Issue by lilx2018** [glepnir/nvim#49]
首先多谢大神！我觉得这个配置真是又快又好！

在 windows 下安装最新的代码（db14cd7fcdae24b45d42dd87e764f964f837a2fc）成功，但发现有几个现象，不知是不是问题，以及是什么缘故。

1. 似乎多数情况下不显示状态条，启动后通过 :set laststatus 返回 0，需要手工执行 :set laststatus=2 才有状态条。
2. 选择若干行列之后，没有显示 “--- 可视 ---"，然后在最右边显示选择了多少列（如果只有一行的情况下）或多少行。这个特性有时很有用，比如想查看一个字符串有多少个字符，可以先选中这个字符串，再查看状态显示中的数字就可以知道了。
3. hover 信息（及 PackerInstall 时） 的 border 乱码，具体见图，我已经设置字体为 vim.opt.guifont = "Hasklug NERD Font:h13"，换成其它字体似也一样是乱码。

nvy 显示的乱码：
![image](https://user-images.githubusercontent.com/95909877/188299107-acac709b-88d1-4126-b3e1-811ac07f358d.png)

goneovim 显示的乱码（相对字体小了没那么明显）
![image](https://user-images.githubusercontent.com/95909877/188299157-5cbe38c4-b49f-4175-b8e2-f75a9323f7c7.png)

**Comment by glepnir** [comment]
搞开发就用linux吧。 我十年没用过win了所以在在win下有有问题吧
