### ISSUE TITLE
How to display the warnings on the status line?

### ISSUE THREAD

**Issue by Fenriuz** [glepnir/nvim#5]
The status line only shows me the number of errors, but does not show me the warnings.
The same happens when I use diagnostic-languageserver with eslint.

![image](https://user-images.githubusercontent.com/63080658/104407844-37e8f980-5528-11eb-9482-e0eecf93ea81.png)

**Comment by glepnir** [comment]
Now should be support.

**Comment by Fenriuz** [comment]
I had already tried DiagnosticHint and it did not work for me either
I tried the updates you just did and it doesn't work either
I think something is wrong with the Lsp

**Comment by glepnir** [comment]
Seems like diagnostic-languageserver doesn't work with builtin-lsp? can you tried the matt/efm server

**Comment by Fenriuz** [comment]
I managed to fix it by modifying three lines of code in the galaxyline plugin. If you want, I can make a pull request, take a look

**Comment by glepnir** [comment]
of course you can make pr in galaxyline.
