### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NikolaM-Dev** [glepnir/nvim#51]
Did you put your other private dotfiles?
Will they become public again?
I love your tmux config among other things 😅. Sorry for the contact method...

**Comment by glepnir** [comment]
no .  I will add you into my private dotfiles.

**Comment by NikolaM-Dev** [comment]
Thank you very much

**Comment by Meuko** [comment]
@glepnir , if at all possible, could you add me also?

**Comment by glepnir** [comment]
I had invited you
