### ISSUE TITLE
怎样使用

### ISSUE THREAD

**Issue by ilkl** [glepnir/nvim#6]
这个配置很好，但我拷过来后报这个错：
E5113: Error while calling lua chunk: Vim(call):E474: UTF-8 string contains code point which belongs to a surrogate pair: <d83c><df54> ',
      prompt_position = 'top',
      sorting_strategy = 'ascending',
    },
    extensions = {
        fzy_native = {
            override_generic_sorter = false,
            override_file_sorter = true,
        }
    }
  }
  require('telescope').load_extension('fzy_native')
  require'telescope'.load_extension('dotfiles')
  require'telescope'.load_extension('gosource')
EOF

需要安装什么环境呢？

**Comment by glepnir** [comment]
最新的neovim 提交构建

**Comment by ilkl** [comment]
我用的是0.5 ，不需要 lua 环境吗？，但会报错






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Raphael"<notifications@github.com&gt;; 
发送时间: 2021年1月26日(星期二) 晚上10:32
收件人: "glepnir/nvim"<nvim@noreply.github.com&gt;; 
抄送: "爱的是大方"<1059650162@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [glepnir/nvim] 怎样使用 (#6)





 
Closed #6.

**Comment by glepnir** [comment]
0.5最好最近的提交版本构建。

**Comment by ilkl** [comment]
源码直接编译的NVIM v0.5.0-dev+1051-g4d1fc167a ，但还是报错：







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Raphael"<notifications@github.com&gt;; 
发送时间: 2021年1月27日(星期三) 上午9:08
收件人: "glepnir/nvim"<nvim@noreply.github.com&gt;; 
抄送: "爱的是大方"<1059650162@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [glepnir/nvim] 怎样使用 (#6)





 
0.5最好最近的提交版本构建。

**Comment by glepnir** [comment]
utf8 编码？。你可以试试删了telescope 会不会报错。。

**Comment by ilkl** [comment]
报这个错：
E5113:Error while calling lua chunk: /home/xuguanghe/.config/nvim/lua/damain/dein.lua:16Vim121:Undefined variable:most





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Raphael"<notifications@github.com&gt;; 
发送时间: 2021年1月27日(星期三) 上午9:55
收件人: "glepnir/nvim"<nvim@noreply.github.com&gt;; 
抄送: "爱的是大方"<1059650162@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [glepnir/nvim] 怎样使用 (#6)





 
utf8 编码？。你可以试试删了telescope 会不会报错。。

**Comment by ilkl** [comment]
大佬 你哔哩哔哩有号吗 ，有视频我去看看学习学习




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Raphael"<notifications@github.com&gt;; 
发送时间: 2021年1月27日(星期三) 上午9:55
收件人: "glepnir/nvim"<nvim@noreply.github.com&gt;; 
抄送: "爱的是大方"<1059650162@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [glepnir/nvim] 怎样使用 (#6)





 
utf8 编码？。你可以试试删了telescope 会不会报错。。

**Comment by glepnir** [comment]
qq 群吧 :941757196
