### ISSUE TITLE
请问一下你的LSP补全是用那个插件的？

### ISSUE THREAD

**Issue by Jerry-Moo** [glepnir/nvim#64]
研究了一下你LSP 的配置 好像就用了2个插件
```neovim/nvim-lspconfig```
```nvimdev/lspsaga.nvim```
好像没用到 [nvim-cmp](https://github.com/hrsh7th/nvim-cmp)
想问一下你是怎么实现自动补全的功能呢。
特别要引入多个补全源的时候
比如cmp-nvim-lsp/cmp-path/cmp-buffer
Copilot

**Comment by glepnir** [comment]
epoch.lua
