### ISSUE TITLE
epoch completion don't work

### ISSUE THREAD

**Issue by SlippyJimmy** [glepnir/nvim#71]
it cann't confirm choosed result,whether i input `Enter`or `C-y`
<img width="770" alt="image" src="https://github.com/glepnir/nvim/assets/45062658/2cbb2488-47ec-442d-998b-6ec69707611f">
![image](https://github.com/glepnir/nvim/assets/45062658/22b7ab5e-4e0d-4867-9d16-ba9c155ff810)

**Comment by glepnir** [comment]
`:help completeopt`  because i use `noselect` so you may need press tab or ctrl-n to choose item

**Comment by SlippyJimmy** [comment]
I can choose items normally, but when I press the `Enter`or`<Ctrl-Y>`, the period disappears, like in the picture above, connect`fmt`and`Println`.

**Comment by glepnir** [comment]
that's neovim bug and I create a pr on neovim  #24661

**Comment by SlippyJimmy** [comment]
ok,think you

**Comment by glepnir** [comment]
#24661  do fuzzy match and case ignore now . but it just set the option omnifunc . so I plan to add an autocomplete.
