### ISSUE TITLE
Error: UTF-8 string contains code point which belongs to a surrogate pair

### ISSUE THREAD

**Issue by vpeopleonatank** [glepnir/nvim#8]
After run `make install`
I received error
<details><summary>Error log</summary>
<p>

####
```vim
E5113: Error while calling lua chunk: Vim(call):E474: UTF-8 string contains code point which belongs to a surrogate pair: <d83c><df54> ',
      prompt_position = 'top',
      sorting_strategy = 'ascending',
      file_previewer = require'telescope.previewers'.vim_buffer_cat.new
    },
    extensions = {
        fzy_native = {
            override_generic_sorter = false,
            override_file_sorter = true,
        }
    }
  }
  require('telescope').load_extension('fzy_native')
  require'telescope'.load_extension('dotfiles')
  require'telescope'.load_extension('gosource')
EOF
```
</p>
</details>

After that, open nvim also appear this error
![image](https://user-images.githubusercontent.com/30976876/107216622-9d54db00-6a3f-11eb-9372-49a4de1812f5.png)

And i can't use any keybinding

**Comment by glepnir** [comment]
Hmm I don't know what happen ....

**Comment by glepnir** [comment]
seems like your terminal does not support emoji. remove this
https://github.com/glepnir/nvim/blob/8b739088d61a51f9de2bf895b441040ce2353f46/modules/fuzzyfind.yaml#L7

BTW this is my person config ..I did not fix with any issue:)

**Comment by vpeopleonatank** [comment]
> seems like your terminal does not support emoji. remove this
> https://github.com/glepnir/nvim/blob/8b739088d61a51f9de2bf895b441040ce2353f46/modules/fuzzyfind.yaml#L7
> 
> BTW this is my person config ..I did not fix with any issue:)

I use alacritty terminal, when i use vim open `fuzzyfind.yaml` it show correct icon
![image](https://user-images.githubusercontent.com/30976876/107219486-be1f2f80-6a43-11eb-8cbe-341f5801b44f.png)
I tried to use other emoij but it didn't work.
After removing icon in `promp_prefix`, i can use your config normally. D
