### ISSUE TITLE
`opt.completeopt = "menu,menuone,noinsert,fuzzy,popup"` some value of this option i implement on neovim main branch. if you are using release version of neovim remove fuzzy and popup

### ISSUE THREAD

**Issue by grichee** [glepnir/nvim#80]
`opt.completeopt = "menu,menuone,noinsert,fuzzy,popup"` some value of this option i implement on neovim main branch. if you are using release version of neovim remove fuzzy and popup

_Originally posted by @glepnir in https://github.com/glepnir/nvim/issues/79#issuecomment-2559742465_
            
![Screenshot_2024-12-23_18-50-09](https://github.com/user-attachments/assets/8e86c636-5385-4934-961e-bbe623efcb4b)

now this comes

**Comment by glepnir** [comment]
remove     `vim.cmd.packadd('nohlsearch')` in event.lua and i just update with remove

**Comment by grichee** [comment]
> remove `vim.cmd.packadd('nohlsearch')` in event.lua and i just update with remove

i dont use lsp, where can i remove its config if anywhere other than plugins file.

**Comment by glepnir** [comment]
moudles/lsp folder is all of lsp
