### ISSUE TITLE
Automatically indent on new line?

### ISSUE THREAD

**Issue by vpeopleonatank** [glepnir/nvim#9]
When i press `<CR>` or `o`, it didn't indent automatically as shown below
![image](https://user-images.githubusercontent.com/30976876/107305851-5524cf80-6ab6-11eb-984b-10e26159c174.png)

Expected behaviour occur normally in vim and non-configed neovim :
![image](https://user-images.githubusercontent.com/30976876/107305972-9321f380-6ab6-11eb-84a2-c9da519b94b6.png)

**Comment by glepnir** [comment]
remove treesitter indent enable.
